### PR TITLE
Add Cassandra

### PR DESCRIPTION
**Pull request by nfnt**
The Cassandra addon uses the KUDO driver to install the Cassandra operator.

### CODE REVIEW

**Comment by nfnt** [comment]
The test is running into a timeout
```
panic: test timed out after 10m0s
```
I suspect this is because Cassandra needs a lot of resources to deploy. The kind cluster probably doesn't have enough resources. The [CI for the cassandra operator](https://github.com/mesosphere/kudo-cassandra-operator/) uses a konvoy cluster with 10 `t3.xlarge` worker nodes.

**Comment by shaneutt** [comment]
> The test is running into a timeout
> 
> ```
> panic: test timed out after 10m0s
> ```
> 
> I suspect this is because Cassandra needs a lot of resources to deploy. The kind cluster probably doesn't have enough resources. The [CI for the cassandra operator](https://github.com/mesosphere/kudo-cassandra-operator/) uses a konvoy cluster with 10 `t3.xlarge` worker nodes.

Understood. It is possible to use Konvoy via the kubeaddons testing framework, we should look into using that instead of kind for testing Cassandra. Do you have any experience with setting up AWS creds in TC?

**Comment by nfnt** [comment]
I'll look if it's possible to configure the Cassandra deployment to use less resources.

**Comment by nfnt** [comment]
Reduced the number of Cassandra nodes. Also disabled the Prometheus integration which requires Prometheus CRDs. The tests are green now 💚

**Comment by shaneutt** [comment]
Awesome, do you consider this `wip` -> `ready` now @nfnt?

**Comment by nfnt** [comment]
Yes, no longer WIP.

**Pull request merged**
