### PR TITLE
Fix Spark 2.4.5 params.yml reference

### PR DESCRIPTION
**Pull request by kaiwalyajoshi**
Fix Spark 2.4.5 to use the params.yml file associated with [Spark Operator 1.0.1 Release](https://github.com/kudobuilder/operators/commit/d4cbfc347069d1e1f2795525a2c3e04e90b3d8a3)

### CODE REVIEW

**Review by alexeygorobets — APPROVED** [review]
LGTM, Thanks @kaiwalyajoshi

**Review by alembiewski — COMMENTED** [review]
I see the parameters file version doesn't match with the version of the operator:
https://github.com/mesosphere/kubeaddons-enterprise/blob/907b5c9406b11d400b4706c36ff189cd100e5826/addons/spark/1.x/spark-2.yaml#L35
Should we specify `1.0.1` here as well?

**Comment by kaiwalyajoshi** [comment]
@alembiewski fixed, thanks for spotting that!

**Review by alembiewski — APPROVED** [review]
LGTM!

**Pull request merged**
