### PR TITLE
workloads releases of Kafka and Cassandra (#63)

### PR DESCRIPTION
**Pull request by zmalik**
* release Cassandra GA addon
* removes beta label from Cassandra
* bump Kafka addon to 2.5.0 release

### CODE REVIEW

**Comment by zmalik** [comment]
@mesosphere/sig-ksphere-catalog can you have a look?

**Comment by makkes** [comment]
@zmalik:
> The base branch requires all commits to be signed
would you mind signing your commits and force-pushing, please?

**Comment by zmalik** [comment]
> would you mind signing your commits and force-pushing, please? 

this is staging branch and re-signing should be done in `dev` branch to keep the same history in `master` and `dev`

**Comment by juliangieseke** [comment]
the commit in question was added before we enforced signed commits. merged it to master as is to prevent git history mess-up

**Pull request merged**
