### PR TITLE
Add dispatchfile

### PR DESCRIPTION
**Pull request by AliakseiKhomchanka**
Don't mind this PR, still testing things.

### CODE REVIEW

**Comment by makkes** [comment]
Given the PR's description I set the `wip` label.

**Comment by shaneutt** [comment]
@AliakseiKhomchanka please let us know in @mesosphere/sig-ksphere-catalog if there's any assistance you need to help move this one forward!

**Comment by shaneutt** [comment]
@AliakseiKhomchanka it seems like this PR was made for testing, but has gone stale. For the moment we're going to mark it as closed simply to signal that nothing needs to be reviewed here right now, but please feel free to re-open this at any time you need it and contact SIG Catalog in slack if you require any assistance.

**Comment by AliakseiKhomchanka** [comment]
Reopening to test the new image for Dispatch, no reviews or anything needed so far.

**Comment by shaneutt** [comment]
Ok just let us know if you need anything :vulcan_salute:

**Comment by shaneutt** [comment]
Just wanted to check in again on this one?

**Comment by AliakseiKhomchanka** [comment]
I thought I had a question but just realized I've found the answer. Thus nothing so far.

**Comment by shaneutt** [comment]
@AliakseiKhomchanka @zmalik and I are actively looking into completely redoing our CI for this repo to switch to using [kuttl](https://github.com/kudobuilder/kuttl).

In its current state, the Spark tests don't pass so I'm going to close this temporarily, and we should re-open this once we've got the kuttl work done to give it another go.

**Pull request closed without merging**
