### PR TITLE
Merge dev branch into master

### PR DESCRIPTION
**Pull request by rishabh96b**

### CODE REVIEW

**Comment by makkes** [comment]
CI checks are failing with
```
      logger.go:42: 07:57:49 | spark-install-1-x | 2021-02-10 07:49:48 +0000 UTC  Warning  Addon.kubeaddons.mesosphere.io spark    DriverInitFailure  webhook: error when creating resource selfsigned-issuer/kudo-system. Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: x509: certificate signed by unknown authority
08:57:49
      logger.go:42: 07:57:49 | spark-install-1-x | 2021-02-10 07:49:48 +0000 UTC  Warning  Addon.kubeaddons.mesosphere.io spark    DriverInitFailure  error initializing KUDO : CRD operators.kudo.dev is already installed. Did you mean to use --upgrade?
```
Does that ring a bell with you @rishabh96b because I wouldn't have a clue what's happening without having to dig deeper.

**Comment by rishabh96b** [comment]
Thanks for pointing this @makkes! This is a known issue and I've created an issue for this as well.

**Comment by akirillov** [comment]
@makkes, @rishabh96b, this is not a flaky Spark test, but most likely a timing issue in KUDO Driver initialization related to the cert-manager webhook. Proposed fix in this PR: https://github.com/mesosphere/kubeaddons-tests/pull/20

**Comment by akirillov** [comment]
Builds from a PR with the fix pass on the dev branch of this repo:https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_EnterpriseAddonsTests?branch=pull%2F20&buildTypeTab=overview&mode=builds

**Review by kaiwalyajoshi — APPROVED** [review]

**Comment by kaiwalyajoshi** [comment]
Closing in favour of #117

**Pull request closed without merging**
