### PR TITLE
Automated chart bump jenkins-2.5.4

### PR DESCRIPTION
**Pull request by d2iq-dispatch**

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]

**Review by shaneutt — CHANGES_REQUESTED** [review]
@cprovencher did something break here?

**Review by makkes — CHANGES_REQUESTED** [review]
this doesn't bump the chart at all. 🤔

**Comment by makkes** [comment]
Bump has already happened here: https://github.com/mesosphere/kubeaddons-enterprise/pull/82

**Comment by cprovencher** [comment]
invalid

**Pull request closed without merging**
