### PR TITLE
feat: add kudo generic application operator addon

### PR DESCRIPTION
**Pull request by natmegs**
This PR adds the KUDO generic application addon to the enterprise catalog, which allows users to configure their own custom service. Based on the example addon provided in the [kudo operator repo](https://github.com/kudobuilder/generic-application-operator/blob/master/example-addon.yaml). Related [JIRA](https://jira.d2iq.com/browse/D2IQ-66674)

### CODE REVIEW

**Comment by natmegs** [comment]
@shaneutt I've added a brief description let me know if I should provide more details!

**Comment by shaneutt** [comment]
@natmegs from CI:

```
[Step 1/1]     TestValidateUnhandledAddons: addons_test.go:90: the following addons are not handled as part of a testing group: [ generic-application-operator]
```

New addons need to have tests added for them for CI to pass. Let @mesosphere/sig-ksphere-catalog  know if you have any questions or need any assistance in this regard.

**Comment by shaneutt** [comment]
@natmegs just wanted to ping here, looks like there's still a need for the new addon to get tests to proceed. But since this has been sitting around for months now I wonder, do we even need this addon? :thinking:

**Comment by zmalik** [comment]
@shaneutt there are tests now for this generic-operator 
added here:  https://github.com/mesosphere/kubeaddons-tests/pull/2

and its ✅ here: https://teamcity.mesosphere.io/buildConfiguration/kubeaddons_EnterpriseAddons/2794154?buildTab=tests&pager.currentPage=1 
@natmegs we would need metadata here https://github.com/mesosphere/kubeaddons-enterprise/tree/dev/metadata/static can you add it?

**Comment by natmegs** [comment]
@zmalik I do not have the description copy or logo for this addon (maybe the team who maintains it could help and add it here?) - is it a blocker for merging this PR? From a strictly UI perspective it will just show with a default logo and no description
Screen Shot 2020-07-07 at 11 04 08 AM

**Comment by natmegs** [comment]
May revisit at a later time

**Pull request closed without merging**
