### PR TITLE
[chore] use new test.Groups

### PR DESCRIPTION
**Pull request by shaneutt**
The purpose of this PR is to switch to using the new test.Groups available in kubeaddons.

This also has to move overrides and dependency removals into code temporarily, but will be followed up in [D2IQ-64927](https://jira.d2iq.com/browse/D2IQ-64927).

This resolves [D2IQ-64898](https://jira.d2iq.com/browse/D2IQ-64898).

### CODE REVIEW

**Comment by shaneutt** [comment]
The code is working correctly, the reason for the build failure is that there's an issue with spark in master that causes the spark test group to fail due to a missing service account. Other test groups are successful.

See that test groups are otherwise running and being identified successfully:

https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2612209&_focus=435

For this one, we should merge through the build failures. cc @zmalik do you have any spare cycles to look at the problems with Spark? it appears the operator can't start it because the spark-init job fails with:

```
  Warning  FailedCreate  69s (x6 over 6m20s)  job-controller  Error creating: pods "spark-init-" is forbidden: error looking up service account default/spark-spark-operator-service-account: serviceaccount "spark-spark-operator-service-account" not found
```

**Comment by zmalik** [comment]
> cc @zmalik do you have any spare cycles to look at the problems with Spark? 

I'm looking into it. 
Not a fan of overrides in code. But I guess we will have a follow-up to move them again out from the code

**Comment by zmalik** [comment]
@shaneutt can I cannot reproduce the issue in the local environment.
Spark operator creates service-account as a separate step from init-job and makes it hard to understand when and why this would happen. 

```
kubectl get sa     
NAME                                   SECRETS   AGE
default                                1         117s
spark-spark-operator-service-account   1         50s
spark-spark-service-account            1         50s
```
cc: @alembiewski @akirillov 

on the other note, I'm reducing resources for cassandra/zk/kafka to make it easier to run in local dev environments. And here we are testing the addon deployment and not the default settings.

**Comment by shaneutt** [comment]
Considering this blocked until some other PR's are shored up

**Comment by zmalik** [comment]
@shaneutt this is definitively a flaky test. I'm bringing https://jira.d2iq.com/browse/D2IQ-64013 to the current sprint. You can merge this PR as long we have ✅in teamcity

**Comment by shaneutt** [comment]
Thanks for the help  @zmalik !

**Pull request merged**
