### PR TITLE
chore: Bump KUTTL to 0.8.0

### PR DESCRIPTION
**Pull request by rishabh96b**

### CODE REVIEW

**Review by farhan5900 — APPROVED** [review]

**Comment by makkes** [comment]
I looked at the CI logs of the failed test:
```
2021-02-11T07:21:37.455443108Z 2021/02/11 07:21:37 WARNING: kudo.dev group has been deprecated and is schedule to be removed in KUTTL 0.8.0
```
It looks like the group hasn't been removed but we should anticipate that. Maybe in this PR? This is not the reason for the failure, though.

I'm not extremely familiar with Dispatch so if @faiq wouldn't mind taking a look, that would be a great help.

**Comment by rishabh96b** [comment]
Related thread for Dispatch issue is here: https://mesosphere.slack.com/archives/CLETZF5U6/p1613026748230000

**Comment by rishabh96b** [comment]
> I looked at the CI logs of the failed test:
> 
> ```
> 2021-02-11T07:21:37.455443108Z 2021/02/11 07:21:37 WARNING: kudo.dev group has been deprecated and is schedule to be removed in KUTTL 0.8.0
> ```
> 
> It looks like the group hasn't been removed but we should anticipate that. Maybe in this PR? This is not the reason for the failure, though.
> 
> I'm not extremely familiar with Dispatch so if @faiq wouldn't mind taking a look, that would be a great help.

@makkes PR to fix the above warning is here: https://github.com/mesosphere/kubeaddons-tests/pull/22

**Comment by kaiwalyajoshi** [comment]
We can merge this after https://github.com/mesosphere/kubeaddons-tests/pull/24 is merged.

**Review by kaiwalyajoshi — APPROVED** [review]

**Review by makkes — APPROVED** [review]

**Pull request merged**
